---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./project/manifest
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-source
  validation: client
